# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RootCAFixer
                                 A QGIS plugin
 This plugin calls hosts using windows' curl.exe, to auto-download missing root CA certificates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-02
        copyright            : (C) 2025 by Tilman Brock-Hesse
        email                : tilman.brock+qgis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RootCAFixer class from file RootCAFixer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rootca_fixer import RootCAFixer
    return RootCAFixer(iface)
