# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RootCAFixerDialog
                                 A QGIS plugin
 This plugin calls hosts using windows' curl.exe, to auto-download missing root CA certificates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tilman Brock-Hesse
        email                : tilman.brock+qgis@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from qgis.core import QgsSettings

import PyQt5 

from urllib.parse import urlparse

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'rootca_fixer_dialog_base.ui'))


class RootCAFixerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(RootCAFixerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        self.cb_use_wmswfs_servers.clicked.connect(self.addWMSWFSServers)
        self.button_clear.clicked.connect(self.clearServerList)
        self.button_add.clicked.connect(self.addServerFromText)
        self.button_fetch.clicked.connect(self.processServers)
        
        self._servers = []

    def _getWMSWFSServerURLs(self):
        """Get a list of distinct WMS and WFS Server URLS (that use https) from the QgsSettings and store in self._servers"""
        
        settings = QgsSettings()
        
        urls = []

        # WMS
        settings.beginGroup("connections/ows/items/wms/connections/items/")
        for g in settings.childGroups():
            raw_url = settings.value(f"{g}/url")
            urls.append(raw_url)
            u = urlparse(raw_url) 
            srv = f"{u.scheme}://{u.netloc}"
            if u.scheme=="https" and not srv in self._servers:
                self._servers.append(srv)
        settings.endGroup()

        # WFS  
        settings.beginGroup("connections/ows/items/wfs/connections/items/")
        for g in settings.childGroups():
            raw_url = settings.value(f"{g}/url")
            urls.append(raw_url)
            u = urlparse(raw_url) 
            srv = f"{u.scheme}://{u.netloc}"
            if u.scheme=="https" and not srv in self._servers:
                self._servers.append(srv)
        settings.endGroup()
                
        return self._servers
        
    def addWMSWFSServers(self):
        self._getWMSWFSServerURLs()
        for s in self._servers:
            self.list_servers.addItem(s)
        self.cb_use_wmswfs_servers.setEnabled(False)
            
    def clearServerList(self):
        self.list_servers.clear()
        self._servers = []
        
    def addServerFromText(self):
        if self.lineedit_server.text() != "":
            u = urlparse(self.lineedit_server.text())
            srv = f"{u.scheme}://{u.netloc}"
            if u.scheme != "https":
                return
            if srv not in self._servers:
                self.list_servers.addItem(srv)
                self._servers.append(srv)
                
    def processServers(self):
        for i in list(range(self.list_servers.count())):
            item = self.list_servers.item(i)
            if not item.text().startswith("✅"):
                self.processOneServer(item)
            
    def processOneServer(self, item):
        server = item.text()
        ### here XXX
        item.setText(f"✅Processed {server}")